server:
  port: ${tian-shan.server.port}

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${tian-shan.datasource.driver-class-name}
      url: jdbc:mysql://${tian-shan.datasource.host}:${tian-shan.datasource.port}/${tian-shan.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ${tian-shan.datasource.username}
      password: ${tian-shan.datasource.password}
  data:
    redis:
      host: ${tian-shan.redis.host}
      port: ${tian-shan.redis.port}
      password: ${tian-shan.redis.password}
      database: ${tian-shan.redis.database}

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.akbar.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# swagger(SpringDoc)配置
springdoc:
  api-docs:
    enabled: true
  group-configs:  # 接口分组配置
    - group: admin
      paths-to-match:
        - /admin/**
    - group: user
      paths-to-match:
        - /user/**

# jwt配置
tian-shan:
  jwt:
    admin-secret-key: TIHGjrruCw2k6DAwcgbPRZvJvvwCwI4xYHZhgrErHs4=
    admin-ttl: 7200000  # 2小时(7200000ms)
    admin-token-name: token
    # 小程序用户端
    user-secret-key: Hyrslz32flxe9r1SGOY3AmSthTjkiOMjtFmdKdOtF+8=
    user-ttl: 7200000
    user-token-name: authentication

  # 阿里云oss配置
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
    region:

  # 微信小程序配置
  wechat:
    appid: ${tian-shan.wechat.appid}
    secret: ${tian-shan.wechat.secret}
    grant_type: ${tian-shan.wechat.grant_type}